
import SideBar from "./components/SideBar";
import "./globals.css";

export const metadata = {
  title: "Admin Dashboard By Next Js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="main w-full">
           <SideBar />
        </main>
        {children}
      </body>
    </html>
  );
}
