
import ThemeProvider from "./context/ThemeProvider";

import "./globals.css";

export const metadata = {
  title: "Admin Dashboard By Next Js",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider> 
              { children }
         </ThemeProvider>
      </body>
    </html>
  );
}
