
import Header from "./components/Header";
import SideBar from "./components/SideBar";

import "./globals.css";

export const metadata = {
  title: "Admin Dashboard By Next Js",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="main w-full">
           <SideBar />
           <div className="right-content pl-[19%]">
             <Header /> 
           </div>
        </main>
        {children}
      </body>
    </html>
  );
}
